version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=crypto_user
      - DATABASE_PASSWORD=CryptoTrack2025!
      - DATABASE_NAME=crypto_tracker
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=CryptoTrack2025!
      - POSTGRES_DB=crypto_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: